import { Roboto } from "next/font/google";
import Header from "@/components/layout/Header";

import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-6xl mx-auto p-5">
          <Header />
          {children}
          <footer className="border-t p-7 text-center font-semibold text-gray-500 mt-9">
            &copy; 2024 All rights reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
